// src/features/tech-stack/components/tech-stack-card.svelte
<script lang="ts">
	import type { TechStack } from '../types';

	export let stack: TechStack;
</script>

<div class="flex min-w-24 flex-col items-center">
	<img
		src={stack.iconUrl ?? 'https://via.placeholder.com/150'}
		alt="{stack.name} icon"
		class="mb-4 h-12 w-auto object-contain grayscale transition duration-300 hover:grayscale-0"
	/>
	<h3 class="mb-2 text-center text-lg font-semibold">{stack.name}</h3>
</div>

// src/entities/tech-stack/ui/tech-stack-card.tsx

import type { TechStack } from "../model/types"

export function TechStackCard({ stack }: { stack: TechStack }) {
  return (
    <div className="flex min-w-24 flex-col items-center">
      <img
        src={stack.image_logo ?? "https://via.placeholder.com/150"}
        alt={`${stack.name} icon`}
        className="mb-4 h-12 w-auto object-contain grayscale transition duration-300 hover:grayscale-0"
        draggable="false"
      />
      <h3 className="mb-2 text-center text-lg font-semibold text-gray-900 dark:text-gray-100">{stack.name}</h3>
    </div>
  )
}
